clubchief/config/routes.rb
Clubchief::Application.routes.draw do
  
  root :to => "home#main"
  match '/home' , :to => 'home#main'


  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}

  resources :event
  match "event/new", :to => "event#new"
  post 'event/create'
  match '/event/not_attending/:id' => 'event#not_attending' ,:as => :not_attending_event
  match '/event/attending/:id' => 'event#attending' ,:as => :attending_event
  match '/event/:event_id/change_status/:attendee_id' => 'event#extern_change_attend_status'

  resources :competitions
  match '/competitions' => 'competitions#index'
  match '/competitions/apply/:competition_id' => 'competitions#apply', :as => :apply_competition
  
  resources :admin_competitions
  match '/competitions/admin' => 'admin_competitions#index'
  match '/competitions/admin/manage/:competition_id' => 'admin_competitions#show', :as => :manage_competition
  match '/competitions/admin/update' => 'admin_competitions#update'
  match '/competitions/admin/remove' => 'admin_competitions#remove'
  match '/competitions/admin/team/new/:competition_id' => 'admin_competitions#add_team', :as => :add_competition_team
  post '/admin_competitions/create_team'

  resources :admin_teams

  match '/teams/admin/:team_id' => 'admin_teams#assign', :as => :competition_team_manage
  match '/teams/admin/create_membership/:team_id/:application_id' => 'admin_teams#create_membership', :as => :create_comp_membership
  match '/teams/admin/remove_membership/:membership_id' => 'admin_teams#remove_membership', :as => :remove_comp_membership
  match '/teams/admin/remove/team/:team_id' => 'admin_teams#destroy', :as => :remove_team
  match '/teams/admin/assign_admin/:user_id/:team_id' => 'admin_teams#assign_admin', :as => :assign_team_admin
  match '/teams/admin/manage/:team_id' => 'admin_teams#manage', :as => :manage_team
  match '/teams/admin/manage/assign/:team_id/:user_id' => 'admin_teams#assign_to_team', :as => :assign_to_team
  match '/teams/admin/manage/unassign/:team_id/:user_id' => 'admin_teams#unassign_from_team', :as => :unassign_from_team

  match  '/teams/admin/rename/:id', :to => 'admin_teams#rename'

  get '/users/admin/new' => 'admin_users#new'
  post '/users/admin/create' => 'admin_users#create'
  match '/users/admin/:club_id' => 'admin_users#index', :as => :manage_club
  match '/users/admin/assign_admin/:club_id/:user_id' => 'admin_users#assign_admin', :as => :assign_admin

  
  match '/applications/admin/new/:competition_id' => 'admin_applications#new', :as => :add_users_to_competition
  match '/applications/admin/create/:competition_id/:user_id' => 'admin_applications#create' , :as => :add_user_to_competition
  
  match '/applications' => 'competition_applications#index'

  resources :clubs
  match "/clubs" ,:to => "clubs#index"
  match "/yourclubs" => "clubs#my_index", :as => "my_clubs"
  match "/clubs/destroy/:club_id" => "clubs#destroy"
  match "/clubs/apply/:id" => "clubs#apply", :as => "apply_club"
  match "/clubs/remove/:id" => "clubs#remove", :as => "remove_club"

  resources :teams

  resources :sports


  get "/notifications/show"
  match "/notifications", :to=> 'notifications#show'
  match "/notifications/new", :to => 'notifications#new'
  post "/notifications/create"
  resources :notifications
  

  resources :users
  match "/users" => "users#show"
  match "/recover" => "users#show_recover", :as => "recover_password"
  match "/users/edit_password/:id" => "users#edit_password"
  match "/users/change_password/:id" => "users#change_password"
  match '/signup', :to => 'users#new'
  match '/recover/send', :to => 'users#send_recover'
  match '/password/update', :to => 'users#update_password'
  match "/users/change_password/:id" => "users#change_password", :as => :change_password

  resources :user_verifications
  match "/user_verifications" => "user_verifications#show"

  resources :sessions
  match '/login', :to => 'sessions#new'
  match '/verify' => "sessions#create", :as => :verify_login
  match '/logout', :to => 'sessions#destroy'

  resources :admin_competitions
  match '/competitions/admin', :to => 'admin_competitions#show'
  
  match '/home/help' => 'home#help'
  resources :home


end

clubchief/app/controllers/admin_users_controller.rb
class AdminUsersController < ApplicationController
  before_filter  :is_a_club_admin?



  def index # needs a bug fix, only pulls the users first club
  	user = get_current_user
  	@club = Club.find(params[:club_id])
		team = @club.teams.where(:club_team => true).first
		@members = []
		@admins = []
		#iterate over all the users and separate out admins
		team.memberships.each do |membership|
			if (membership.admin)
				@admins << membership.user
			else
				@members << membership.user
			end 
    end
  end
  
  def assign_admin
 	if Club.exists?(params[:club_id])
  		club = Club.find(params[:club_id])
  		if User.exists?(params[:user_id])
  			user = User.find(params[:user_id])
  			membership = club.all_member_team.memberships.where(:user_id => user.id).first
  			if membership.update_attributes(:admin => true)
  				flash[:success] = "#{user.full_name} is now a admin of #{club.name}"
  			else
  				flash[:alert] = "#{user.full_name} could not be given permissions for #{club.name}"
  			end
  		else
  			flash[:error] = "This user does not exist"
  		end
  	else
  		flash[:error] = "This club does not exist"
  	end
  	redirect_to :action => :index, :club_id => club.id
  end
  
  def new
  	user = get_current_user
    @user = User.new
    memberships = user.memberships.where(:admin => true)
    @clubs = []
    memberships.each do |membership|
      if membership.team.club_team 
        @clubs << membership.club
      end
    end
  end

  def create
    @user = User.new(params[:user])
    @user.email.downcase!
    @club = Club.find(params[:post][:club_id])
    if valid_email_dns?(@user.email)
    	@user.password = create_password
    	@user.password_confirmation = @user.password
    	if User.find_by_email(@user.email)
    	 	team = @club.all_member_team
    	   	user = User.find_by_email(@user.email)
    	   	if !Membership.find_by_user_id_and_team_id(user.id, team.id)
    	   		team.memberships.create(:user_id => user.id )
    	   		flash[:success] = @user.full_name.to_s + " has been added to " + @club.name.to_s
    	   		#foreach event in the team create a attendee row in the database for the new member
                team.add_user_to_current_events(user)
    	   	else
    	   		flash[:alert] = @user.full_name.to_s+" is already a member of this club"
    	   	end
    	elsif @user.save
    	    UserMailer.admin_signup(@user,@club).deliver
   	    	flash[:success] = @user.full_name.to_s + " has been created and signed up to " + @club.name.to_s
   	    	team = @club.all_member_team
    	   	user = User.find_by_email(@user.email)
    	   	team.memberships.create(:user_id => user.id )
    	 else
    	    	@user.password = ""
    	    	@user.password_confirmation = ""
    	 end
    else
    	@user.password = ""
  	@user.password_confirmation = ""
	flash[:alert] = "Please enter a valid email address."
    end
    redirect_to :back
  end

end

clubchief/app/helpers/admin_users_helper.rb
module AdminUsersHelper
end

clubchief/app/views/admin_users/index.html.erb
<h1><%= @club.name.capitalize %> member list</h1>
<div class="list">
<% @admins.each do |admin| %>
      <div class="row">
        <div class="row_left">
		    <h3><%= admin.full_name %></h3>
        </div>
        <span class="admin_icon right" ></span>
      </div>
<% end %>

<% @members.each do |member| %>
      <div class="row">
        <div class="row_left">
		    <h3><%= member.full_name %></h3>
        </div>
        <%= link_to "", assign_admin_path(:user_id => member.id, :club_id => @club.id), :class=>"make_admin_icon right"%>
      </div>
<% end %>
</div>
<%= link_to "Back", my_clubs_path , :class =>"button back_btn left"%>
<%= link_to "Add new member", users_admin_new_path , :class =>"button add_wide_btn left" %>

clubchief/app/views/admin_users/new.html.erb
<h1>Add  a new user</h1>

<% form_for @user , :url => {:controller => "admin_users" , :action => "create"} do |f| %>
<div class="content round">
  
<% if @clubs.length > 1 %>
			 <label class="input-label">
            		<%=  collection_select :post, :club_id, @clubs, :id, :name, {:include_blank => 'Select club'},{:class => 'combobox' } %> <br />
      		</label>
<% else %>
			<%= hidden_field :post, :club_id, :value => @clubs.first.id %>
<% end %>

    	<label class="input-label">
   		<%=  f.text_field :first_name , :maxlength => 20,  :class=>"textbox" , :placeholder => "First Name" %>
   		</label>
   		<br />
    	<label class="input-label">
   		<%=  f.text_field :last_name , :maxlength => 20,  :class=>"textbox" , :placeholder => "Last Name" %>
   		</label>
   		<br />
    	<label class="input-label">
   		<%=  f.text_field :email , :maxlength => 60,  :class=>"textbox" , :placeholder => "Email" %>
   		</label>
   		<br />
  		<%= f.submit "Add user" , :class=>"button add_btn" %>

<% end %>
</div>
<script type="text/javascript">
   $(function(){
      $(".textbox").addPlaceholder();
      $("#user_first_name").validate({
            expression: "if (VAL) return true; else return false;",
            message: "Please enter a first name",
            error_field_class: "field_with_errors",
            error_class: "error_message"
        });
      $("#user_last_name").validate({
            expression: "if (VAL) return true; else return false;",
            message: "Please enter a last name",
            error_field_class: "field_with_errors",
            error_class: "error_message"
      });
      $("#user_email").validate({
            expression: "if (VAL.match(/^[^\\W][a-zA-Z0-9\\_\\-\\.]+([a-zA-Z0-9\\_\\-\\.]+)*\\@[a-zA-Z0-9_]+(\\.[a-zA-Z0-9_]+)*\\.[a-zA-Z]{2,4}$/)) return true; else return false;",
            message: "Please enter a valid email",
            error_field_class: "field_with_errors",
            error_class: "error_message"
        });
   });
</script>