clubchief/config/routes.rb
Clubchief::Application.routes.draw do
  
  root :to => "home#main"
  match '/home' , :to => 'home#main'


  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}

  resources :event
  match "event/new", :to => "event#new"
  post 'event/create'
  match '/event/not_attending/:id' => 'event#not_attending' ,:as => :not_attending_event
  match '/event/attending/:id' => 'event#attending' ,:as => :attending_event
  match '/event/:event_id/change_status/:attendee_id' => 'event#extern_change_attend_status'

  resources :competitions
  match '/competitions' => 'competitions#index'
  match '/competitions/apply/:competition_id' => 'competitions#apply', :as => :apply_competition
  
  resources :admin_competitions
  match '/competitions/admin' => 'admin_competitions#index'
  match '/competitions/admin/manage/:competition_id' => 'admin_competitions#show', :as => :manage_competition
  match '/competitions/admin/update' => 'admin_competitions#update'
  match '/competitions/admin/remove' => 'admin_competitions#remove'
  match '/competitions/admin/team/new/:competition_id' => 'admin_competitions#add_team', :as => :add_competition_team
  post '/admin_competitions/create_team'

  resources :admin_teams

  match '/teams/admin/:team_id' => 'admin_teams#assign', :as => :competition_team_manage
  match '/teams/admin/create_membership/:team_id/:application_id' => 'admin_teams#create_membership', :as => :create_comp_membership
  match '/teams/admin/remove_membership/:membership_id' => 'admin_teams#remove_membership', :as => :remove_comp_membership
  match '/teams/admin/remove/team/:team_id' => 'admin_teams#destroy', :as => :remove_team
  match '/teams/admin/assign_admin/:user_id/:team_id' => 'admin_teams#assign_admin', :as => :assign_team_admin
  match '/teams/admin/manage/:team_id' => 'admin_teams#manage', :as => :manage_team
  match '/teams/admin/manage/assign/:team_id/:user_id' => 'admin_teams#assign_to_team', :as => :assign_to_team
  match '/teams/admin/manage/unassign/:team_id/:user_id' => 'admin_teams#unassign_from_team', :as => :unassign_from_team

  match  '/teams/admin/rename/:id', :to => 'admin_teams#rename'

  get '/users/admin/new' => 'admin_users#new'
  post '/users/admin/create' => 'admin_users#create'
  match '/users/admin/:club_id' => 'admin_users#index', :as => :manage_club
  match '/users/admin/assign_admin/:club_id/:user_id' => 'admin_users#assign_admin', :as => :assign_admin

  
  match '/applications/admin/new/:competition_id' => 'admin_applications#new', :as => :add_users_to_competition
  match '/applications/admin/create/:competition_id/:user_id' => 'admin_applications#create' , :as => :add_user_to_competition
  
  match '/applications' => 'competition_applications#index'

  resources :clubs
  match "/clubs" ,:to => "clubs#index"
  match "/yourclubs" => "clubs#my_index", :as => "my_clubs"
  match "/clubs/destroy/:club_id" => "clubs#destroy"
  match "/clubs/apply/:id" => "clubs#apply", :as => "apply_club"
  match "/clubs/remove/:id" => "clubs#remove", :as => "remove_club"

  resources :teams

  resources :sports


  get "/notifications/show"
  match "/notifications", :to=> 'notifications#show'
  match "/notifications/new", :to => 'notifications#new'
  post "/notifications/create"
  resources :notifications
  

  resources :users
  match "/users" => "users#show"
  match "/recover" => "users#show_recover", :as => "recover_password"
  match "/users/edit_password/:id" => "users#edit_password"
  match "/users/change_password/:id" => "users#change_password"
  match '/signup', :to => 'users#new'
  match '/recover/send', :to => 'users#send_recover'
  match '/password/update', :to => 'users#update_password'
  match "/users/change_password/:id" => "users#change_password", :as => :change_password

  resources :user_verifications
  match "/user_verifications" => "user_verifications#show"

  resources :sessions
  match '/login', :to => 'sessions#new'
  match '/verify' => "sessions#create", :as => :verify_login
  match '/logout', :to => 'sessions#destroy'

  resources :admin_competitions
  match '/competitions/admin', :to => 'admin_competitions#show'
  
  match '/home/help' => 'home#help'
  resources :home


end

clubchief/app/controllers/admin_teams_controller.rb
class AdminTeamsController < ApplicationController
  before_filter :is_a_club_admin?

#This method will allow the admin to assign memebers to a competition team
  def assign
    if Team.exists?(params[:team_id])
      @team = Team.find(params[:team_id])
      if @team.competition.deadline < Time.now
        if @team.competition.competition_finshed == false
              competition = @team.competition
              @unassigned_applications = competition.competition_applications.where(:assiged_to_team => false)
              @assigned_members =[]
              @assigned_admin = []
              @team.memberships.each do |membership|
          		if membership.admin
          			@assigned_admin << membership
          		else
          			@assigned_members << membership
          		end
          end
        else
          flash[:notice] = "You cannot assign members to a team after its competition is finished"
          redirect_to :controller => 'admin_competitions'
        end
      else
        flash[:notice] = "You cannot assign members to a team before the deadline"  
        redirect_to :controller => 'admin_competitions'
      end
    else
      flash[:alert] = "That team does not exist"
      redirect_to :controller => 'admin_competitions'
    end
  end

# This method will assign a member of the competition to a competition team
  def create_membership
  
    if CompetitionApplication.exists?(params[:application_id])
      if Team.exists?(params[:team_id])      
        application = CompetitionApplication.find(params[:application_id])
        team = Team.find(params[:team_id])      
        if team.memberships.create(:user_id => application.user_id)
          application.update_attributes(:assiged_to_team => true)
          team.add_user_to_current_events(application.user_id)
          flash[:success] = application.user.full_name.to_s + " was successfully added to "+ team.name
        else
          flash[:error] = application.user.full_name.to_s +" was not able to be added to "+ team.name
        end
      else
        flash[:alert] = "That team does not exist"
      end
    else
      flash[:alert] = "That application does not exist"
    end
    redirect_to :back  
  end


#this method will remove a membership from a competition team.
  def remove_membership
  	if Membership.exists?(params[:membership_id])
  	    membership = Membership.find(params[:membership_id])
  	    team = membership.team
  	    user = membership.user
  	    if Membership.delete(membership)
          #change the users application so say that they are not part of a team.
  	      application = CompetitionApplication.find_by_user_id_and_competition_id(user.id, team.competition_id)
  	      application.update_attributes(:assiged_to_team => false)
          #remove the user from any future events for this team.
          team.remove_user_from_current_events(user.id)
  	      flash[:success] = user.full_name.to_s + " was successfully removed from the "+ team.name
  	    else
  	      flash[:error] = "This membership was not able to be deleted"
  	    end
  	  else
  	    flash[:alert] ="That membership does not exist"
  	  end 
  	  redirect_to :back  
  end


#this method will delete a team
  def destroy
    if Team.exists?(params[:team_id])
      team = Team.find(params[:team_id])
      if !team.memberships.any?
        Team.delete(team) 
        flash[:success] = team.name.to_s + " team was successfully removed."
      else
        flash[:alert] = "Cannot delete a team with members in it."
      end
    else
      flash[:alert] = "That team does not exist."
    end
    redirect_to :back
  end
  

  #Assign a player in a team to have admin rights of that team
  def assign_admin
  	if Team.exists?(params[:team_id])
  		if User.exists?(params[:user_id])
  			team = Team.find(params[:team_id])
  			user = User.find(params[:user_id])
  			if membership = user.memberships.where(:team_id => team.id).first()
  				if membership.update_attributes(:admin => true)
  					flash[:success] = "#{user.full_name} has bee assigned admin of team #{team.name}."
  				end
  			else
  				flash[:error] = "#{user.full_name} is not a member of #{team.full_name}."
  			end
  		else
  			flash[:error] = "This User does not exist."
  		end
  	else
  		flash[:error] = "This team does not exist."
  	end
  	redirect_to :back
  end
  
  #this is for admin to manage teams not connected to a competition
  def manage
    @team = Team.find(params[:team_id])
    @admin_team_players = @team.memberships.where(:admin => true).collect{|membership| membership.user }
    @team_players = @team.memberships.where(:admin => false).collect{|membership| membership.user }
    @avalible_players = @team.club.all_member_team.users
    @avalible_players = @avalible_players - @team_players
    @avalible_players = @avalible_players - @admin_team_players
  end
  
  #assign a member of the teams club to the team
  def assign_to_team
  	  if Team.exists?(params[:team_id])
  		if User.exists?(params[:user_id])
  			team = Team.find(params[:team_id])
  			user = User.find(params[:user_id])
  			if user.memberships.where(:team_id => team.id).first()
  				flash[:error] = "#{user.full_name} is already a member of #{team.full_name}."
  			else
  				user.memberships.create(:team_id => team.id)
          team.add_user_to_current_events(user.id)
  			end
  		else
  			flash[:error] = "This User does not exist."
  		end
  	else
  		flash[:error] = "This team does not exist."
  	end
  	redirect_to :back
  end
  
  #remove a memeber from this team
  def unassign_from_team
  	 if User.exists?(params[:user_id])
  	 	if Team.exists?(params[:team_id])
  	    		team = Team.find(params[:team_id])
  	    		user = User.find(params[:user_id])
  	    		membership = Membership.find_by_user_id_and_team_id(user.id,team.id)
  	    		if Membership.delete(membership)
  	      		team.remove_user_from_current_events(user.id)
              flash[:success] = user.full_name.to_s + " was successfully removed from the "+ team.name+ "."
            else
       				flash[:error] = "This membership was not able to be deleted"
  	 		end
  	 	else
  	 		flash[:alert] ="That team does not exist"
  	 	end
  	 else
  	 	flash[:alert] ="That user does not exist"
  	 end 
  	  redirect_to :back  
  end
  
  def rename
        team = Team.find(params[:id])
        team.update_attributes(:name => params[:newName])
        redirect_to :back
  end

end

clubchief/app/views/admin_teams/assign.html.erb
<h1>Manage <%= @team.name %></h1>
<h2 class="list_title left">Your team</h2><h2 class="list_title right">Available players</h2>
<br class="clear" />
<div class="list_short left">

  <% if @assigned_admin.count() > 0 || @assigned_members.count() > 0 %>
      <% @assigned_admin.each do |membership| %>
          <div class="row_short">
            <span class="admin_icon left" ></span>
            <h3 class="left"><%= membership.user.full_name %></h3>
            <%= link_to "", remove_comp_membership_path(membership.user_id), :class => "remove_icon right" %>

          </div>
      <% end %>
      <% @assigned_members.each do |membership| %>
          <div class="row_short">
            <%= link_to "", assign_team_admin_path(:user_id => membership.user_id, :team_id => @team.id), :class => "make_admin_icon left" %>
            <h3 class="left"><%= membership.user.full_name %></h3>
            <%= link_to "", remove_comp_membership_path(membership.id), :class => "remove_icon right" %>

          </div>
      <% end %>
  <% else %>
      <div class="row_short" style="background:  none;">
        <h3>There are no members assigned to <%= @team.name %></h3>
      </div>
  <% end %>
</div>

<div class="list_short right">

  <% @unassigned_applications.each do |application| %>
      <div class="row_short">
        <h3 class="left"><%= application.user.full_name %></h3>
        <%= link_to "", create_comp_membership_path(:team_id=>@team.id, :application_id=>application.id), :class => "add_icon right" %>
      </div>
  <% end %>
</div>
<br class="clear" />
<%= link_to "All teams", teams_path, :class => "button back_btn left" %>
<%= link_to "Competition teams", manage_competition_path(@team.competition_id), :class => "button login_wide_btn left" %>

clubchief/app/views/admin_teams/manage.html.erb
<h1>Manage <%= @team.name %></h1>
<h2 class="list_title left">Your team</h2><h2 class="list_title right">Available players</h2>
<br class="clear" />
<div class="list_short left">
  <% if @admin_team_players.count() > 0 || @team_players.count() > 0 %>
      <% @admin_team_players.each do |player| %>
          <div class="row_short">
            <span class="admin_icon left" ></span>
            <h3 class="left"><%= player.full_name %></h3>
            <%= link_to "", unassign_from_team_path(:team_id => @team.id, :user_id => player.id), :class => "remove_icon right" %>

          </div>
      <% end %>
      <% @team_players.each do |player| %>
          <div class="row_short">
            <%= link_to "", assign_team_admin_path(:user_id => player.id, :team_id => @team.id), :class => "make_admin_icon left" %>
            <h3 class="left"><%= player.full_name %></h3>
            <%= link_to "", unassign_from_team_path(:team_id => @team.id, :user_id => player.id), :class => "remove_icon right" %>


          </div>

      <% end %>
  <% else %>
      <div class="row_short" style="background:  none;">
        <h3>There are no members assigned to <%= @team.name %></h3>
      </div>
  <% end %>
</div>

<div class="list_short right">
  <% @avalible_players.each do |player| %>
      <div class="row_short">
        <h3 class="left"><%= player.full_name %></h3>
        <%= link_to "", assign_to_team_path(:team_id => @team.id, :user_id => player.id), :class => "add_icon right" %>
      </div>
  <% end %>
</div>

<br class="clear"/>
<%= link_to "Back", teams_path, :class => "button back_btn" %>