clubchief/config/routes.rb
Clubchief::Application.routes.draw do
  
  root :to => "home#main"
  match '/home' , :to => 'home#main'


  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}

  resources :event
  match "event/new", :to => "event#new"
  post 'event/create'
  match '/event/not_attending/:id' => 'event#not_attending' ,:as => :not_attending_event
  match '/event/attending/:id' => 'event#attending' ,:as => :attending_event
  match '/event/:event_id/change_status/:attendee_id' => 'event#extern_change_attend_status'

  resources :competitions
  match '/competitions' => 'competitions#index'
  match '/competitions/apply/:competition_id' => 'competitions#apply', :as => :apply_competition
  
  resources :admin_competitions
  match '/competitions/admin' => 'admin_competitions#index'
  match '/competitions/admin/manage/:competition_id' => 'admin_competitions#show', :as => :manage_competition
  match '/competitions/admin/update' => 'admin_competitions#update'
  match '/competitions/admin/remove' => 'admin_competitions#remove'
  match '/competitions/admin/team/new/:competition_id' => 'admin_competitions#add_team', :as => :add_competition_team
  post '/admin_competitions/create_team'

  resources :admin_teams

  match '/teams/admin/:team_id' => 'admin_teams#assign', :as => :competition_team_manage
  match '/teams/admin/create_membership/:team_id/:application_id' => 'admin_teams#create_membership', :as => :create_comp_membership
  match '/teams/admin/remove_membership/:membership_id' => 'admin_teams#remove_membership', :as => :remove_comp_membership
  match '/teams/admin/remove/team/:team_id' => 'admin_teams#destroy', :as => :remove_team
  match '/teams/admin/assign_admin/:user_id/:team_id' => 'admin_teams#assign_admin', :as => :assign_team_admin
  match '/teams/admin/manage/:team_id' => 'admin_teams#manage', :as => :manage_team
  match '/teams/admin/manage/assign/:team_id/:user_id' => 'admin_teams#assign_to_team', :as => :assign_to_team
  match '/teams/admin/manage/unassign/:team_id/:user_id' => 'admin_teams#unassign_from_team', :as => :unassign_from_team

  match  '/teams/admin/rename/:id', :to => 'admin_teams#rename'

  get '/users/admin/new' => 'admin_users#new'
  post '/users/admin/create' => 'admin_users#create'
  match '/users/admin/:club_id' => 'admin_users#index', :as => :manage_club
  match '/users/admin/assign_admin/:club_id/:user_id' => 'admin_users#assign_admin', :as => :assign_admin

  
  match '/applications/admin/new/:competition_id' => 'admin_applications#new', :as => :add_users_to_competition
  match '/applications/admin/create/:competition_id/:user_id' => 'admin_applications#create' , :as => :add_user_to_competition
  
  match '/applications' => 'competition_applications#index'

  resources :clubs
  match "/clubs" ,:to => "clubs#index"
  match "/yourclubs" => "clubs#my_index", :as => "my_clubs"
  match "/clubs/destroy/:club_id" => "clubs#destroy"
  match "/clubs/apply/:id" => "clubs#apply", :as => "apply_club"
  match "/clubs/remove/:id" => "clubs#remove", :as => "remove_club"

  resources :teams

  resources :sports


  get "/notifications/show"
  match "/notifications", :to=> 'notifications#show'
  match "/notifications/new", :to => 'notifications#new'
  post "/notifications/create"
  resources :notifications
  

  resources :users
  match "/users" => "users#show"
  match "/recover" => "users#show_recover", :as => "recover_password"
  match "/users/edit_password/:id" => "users#edit_password"
  match "/users/change_password/:id" => "users#change_password"
  match '/signup', :to => 'users#new'
  match '/recover/send', :to => 'users#send_recover'
  match '/password/update', :to => 'users#update_password'
  match "/users/change_password/:id" => "users#change_password", :as => :change_password

  resources :user_verifications
  match "/user_verifications" => "user_verifications#show"

  resources :sessions
  match '/login', :to => 'sessions#new'
  match '/verify' => "sessions#create", :as => :verify_login
  match '/logout', :to => 'sessions#destroy'

  resources :admin_competitions
  match '/competitions/admin', :to => 'admin_competitions#show'
  
  match '/home/help' => 'home#help'
  resources :home


end

clubchief/app/controllers/admin_competitions_controller.rb
class AdminCompetitionsController < ApplicationController
  before_filter  :is_a_club_admin?


  def index
    user = get_current_user
    memberships = user.memberships.where(:admin => true)
    @competitions = []
    memberships.each do |membership|
      if membership.team.club_team 
        membership.team.club.competitions.each do |competition|
            @competitions << competition
        end
      end
    end
  end

  def show
    if Competition.exists?(params[:competition_id])
      @competition = Competition.find(params[:competition_id])
      if @competition.competition_finshed == false
        if @competition.deadline < Time.now 
          @teams = @competition.teams
          @applications = @competition.competition_applications
        else
          flash[:alert] = @competition.name+" has not met it's deadline yet"
          redirect_to :action => 'index'      
        end
      else
        flash[:alert] = @competition.name+" has finshed and can no longer be sorted"
        redirect_to :action => 'index'  
      end
    else
      flash[:alert] = "Sorry that competition does not exist"
      redirect_to :action => 'index' 
    end

  end

  def new
    @competition = Competition.new
  end

  def create
  	@competition = Competition.new(params[:competition])
  	if @competition.save
      flash[:success] = "Successfully created the competition: " + @competition.name
  		redirect_to admin_competitions_path
    else
      flash[:alert] = "Unable to create competition"
    	render "new"
    end
  end
  
  def edit
  	@competition = Competition.find(params[:id])
  end
  
  def update
  	@competition =  Competition.find(params[:id])
  	if @competition.update_attributes(params[:competition])
      flash[:success] = "Successfully updated the competition: " + @competition.name
  		redirect_to  admin_competitions_path
    else
      flash[:alert] = "Unable to update competition"
  		render "edit"
  	end
  end
  
  def destroy
  	if Competition.exists?(params[:id])
  		competition = Competition.find(params[:id])
  		if competition.competition_applications.count == 0
  			if Competition.delete(competition)
  				flash[:success] = "Successfully removed " + competition.name
  			else
  				flash[:alert] = "Unable to remove " + competition.name
  			end
  		else
  			flash[:alert] = "Unable to remove " + competition.name + " because it has applicants"
  		end
  	else
  		flash[:alert] = "This competition does not exist."
  	end
  	redirect_to :back
  end

  def add_team
     @competition =  Competition.find(params[:competition_id])
  end
  
    def create_team
    team = Team.new(params[:team])
    if !team.name.empty?
      if team.save
        flash[:success] = "You have successfully created team '"+team.name+"'"
      else
        flash[:alert] = "Your new team was not able to be saved"
      end
  else
    flash[:alert] = "A new team needs to have a name"
  end
    redirect_to manage_competition_path(params[:team][:competition_id])
  end
  
end

clubchief/app/views/admin_competitions/add_team.html.erb
<h1>Add New Team</h1>
<% form_for Team.new , :url => { :controller => :admin_competitions, :action => :create_team } do |f|%>
          <%= f.hidden_field :club_id, :value => @competition.club_id %>
          <%= f.hidden_field :competition_id, :value =>@competition.id %>
          <%= f.text_field :name, :class => "textbox", :placeholder=>"Team name" %><br />
          <%= f.submit "Add team", :class => "button add_btn"%>
<% end %>

<%= link_to "Back", manage_competition_path(@competition.id), :class => "button back_btn" %>
<script type="text/javascript">
    $(".textbox").addPlaceholder();
</script>

clubchief/app/views/admin_competitions/edit.html.erb
<h1>Edit <%= @competition.name %></h1>


    <%= form_for @competition, :url => {:controller => 'admin_competitions',:action => 'update', :id => @competition.id} do |f| %>

      <label class="input-label">
   		<%=  f.text_field :name ,  :class=>"textbox" , :placeholder => "Competition name" %>
      </label>
          <br/>
   	<label class="input-label">
   			<%=  f.text_field :deadline, :value => @competition.deadline.strftime('%d/%m/%Y')  ,  :class=>"textbox" , :placeholder => "Competition deadline" %>
    </label>
    <br />
    <%= f.submit "Save changes", :class=>"button edit_wide_btn" %>

    <% end %>
<%= link_to 'Back', admin_competitions_path, :class=>"button back_btn" %>

<script>
	$(document).ready(function(){	
			$('#competition_deadline').datepicker({
        			dateFormat: 'dd/mm/yy',
					minDate: new Date()
			});
	});
</script>

clubchief/app/views/admin_competitions/index.html.erb
<h1>Manage competitions</h1>

<% if @competitions.count() > 0 %>
    <div class="list">
    <% @competitions.each do |competition| %>
        <% applicantCount = competition.competition_applications.count %>
        <div class="row_top"></div>
        <div class="row_extend">
            <span class="row_left">
              <div class="row_header"><%= competition.name %></div>
              Club: <%= competition.club.name %><br />
              Applicants: <%= applicantCount %>
            </span>
            <span class="row_right" style="margin-right: 20px;">
                <% if applicantCount == 0 %>
                    <%= link_to "", admin_competition_path(competition), :confirm => 'Are you sure?', :method => :delete, :class => "delete_icon right" %>
                <% end %>
                <% if competition.deadline < Date.today %>
                    <%= link_to "", manage_competition_path(competition.id), :class=>"manage_icon right" %>
                <% end %>
                    <%= link_to "", edit_admin_competition_path(competition), :class => "edit_icon right" %>
            </span>
            <div class="clear"></div>
        </div>
        <div class="row_bottom"></div>
    <% end %>
    </div>
<% else %>
    <h2>You currently have no competitions to manage</h2>
<% end %>
<%= link_to "Add competition", new_admin_competition_path, :class=>"button add_wide_btn" %>

clubchief/app/views/admin_competitions/new.html.erb
<h1>Create Competition</h1>

<%= form_for @competition , :url => { :controller=> "admin_competitions", :action => "create" } do |f| %>
  <% @admin_clubs = get_admin_clubs %>
  <% if @admin_clubs.count > 1 %>
	      <label class="input-label">
        		<%=  f.collection_select :club_id, @admin_clubs, :id, :name,
                              {:include_blank => 'Select a Club'}, {:class => 'combobox'} %>
  		</label>
        <br />
  <% else %>
  		<%= f.hidden_field :club_id, :value => @admin_clubs.first.id %>
  <% end %>
  
   	<label class="input-label">
   			<%=  f.text_field :name , :maxlength => 40,  :class=>"textbox" , :placeholder => "Competition name" %>
    </label>
    <br/>
   	<label class="input-label">
   			<%=  f.text_field :deadline ,  :class=>"textbox" , :placeholder => "Competition deadline" %>
    </label>
    <br />
    <%= f.submit "Add competition", :class=>"button add_wide_btn"%>
  <% end %>

<script>
    $(function(){
      $(".textbox").addPlaceholder();
      $("#competition_name").validate({
            expression: "if (VAL) return true; else return false;",
            message: "Please enter a competition name",
            error_field_class: "field_with_errors",
            error_class: "error_message"
      });
      $("#competition_deadline").validate({
            expression: "if (VAL) return true; else return false;",
            message: "Please enter a valid competition deadline",
            error_field_class: "field_with_errors",
            error_class: "error_message"
      });
      $("#competition_club_id").validate({
            expression: "if (VAL) return true; else return false;",
            message: "Please select a club for the competition",
            error_field_class: "field_with_errors",
            error_class: "error_message"
      });
      $('#competition_deadline').datepicker({
        	dateFormat: 'dd/mm/yy',
            defaultDate: +1,
			minDate: +1
	  });
   });
</script>

clubchief/app/views/admin_competitions/show.html.erb
<h1><%= @competition.name %></h1>

<%= link_to "Add team", add_competition_team_path(), :class => "add_team button add_btn left", :style => "margin-top: 0;" %>
<%= link_to "Add applicants", add_users_to_competition_path(@competition.id), :class => "button add_wide_btn left", :style => "margin-top: 0;" %>
<br class="clear" />
<br />
<h1>Manage Teams</h1>
<div class="list">
  <% @teams.each do |team| %>
  <div class="row">
    <h3><%= team.name %>(<%= team.memberships.count %>)</h3>
      <% if !team.memberships.any? %>
        <%= link_to "", remove_team_path(team.id), :class => "delete_icon right" %>
      <% end %>
      <%= link_to "", competition_team_manage_path(team.id), :class => "manage_icon right" %>
  </div>
  <% end %>
</div>

<%= link_to "Back", admin_competitions_path, :class => "button back_btn clear" %>