clubchief/config/routes.rb
Clubchief::Application.routes.draw do
  
  root :to => "home#main"
  match '/home' , :to => 'home#main'


  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}

  resources :event
  match "event/new", :to => "event#new"
  post 'event/create'
  match '/event/not_attending/:id' => 'event#not_attending' ,:as => :not_attending_event
  match '/event/attending/:id' => 'event#attending' ,:as => :attending_event
  match '/event/:event_id/change_status/:attendee_id' => 'event#extern_change_attend_status'

  resources :competitions
  match '/competitions' => 'competitions#index'
  match '/competitions/apply/:competition_id' => 'competitions#apply', :as => :apply_competition
  
  resources :admin_competitions
  match '/competitions/admin' => 'admin_competitions#index'
  match '/competitions/admin/manage/:competition_id' => 'admin_competitions#show', :as => :manage_competition
  match '/competitions/admin/update' => 'admin_competitions#update'
  match '/competitions/admin/remove' => 'admin_competitions#remove'
  match '/competitions/admin/team/new/:competition_id' => 'admin_competitions#add_team', :as => :add_competition_team
  post '/admin_competitions/create_team'

  resources :admin_teams

  match '/teams/admin/:team_id' => 'admin_teams#assign', :as => :competition_team_manage
  match '/teams/admin/create_membership/:team_id/:application_id' => 'admin_teams#create_membership', :as => :create_comp_membership
  match '/teams/admin/remove_membership/:membership_id' => 'admin_teams#remove_membership', :as => :remove_comp_membership
  match '/teams/admin/remove/team/:team_id' => 'admin_teams#destroy', :as => :remove_team
  match '/teams/admin/assign_admin/:user_id/:team_id' => 'admin_teams#assign_admin', :as => :assign_team_admin
  match '/teams/admin/manage/:team_id' => 'admin_teams#manage', :as => :manage_team
  match '/teams/admin/manage/assign/:team_id/:user_id' => 'admin_teams#assign_to_team', :as => :assign_to_team
  match '/teams/admin/manage/unassign/:team_id/:user_id' => 'admin_teams#unassign_from_team', :as => :unassign_from_team

  match  '/teams/admin/rename/:id', :to => 'admin_teams#rename'

  get '/users/admin/new' => 'admin_users#new'
  post '/users/admin/create' => 'admin_users#create'
  match '/users/admin/:club_id' => 'admin_users#index', :as => :manage_club
  match '/users/admin/assign_admin/:club_id/:user_id' => 'admin_users#assign_admin', :as => :assign_admin

  
  match '/applications/admin/new/:competition_id' => 'admin_applications#new', :as => :add_users_to_competition
  match '/applications/admin/create/:competition_id/:user_id' => 'admin_applications#create' , :as => :add_user_to_competition
  
  match '/applications' => 'competition_applications#index'

  resources :clubs
  match "/clubs" ,:to => "clubs#index"
  match "/yourclubs" => "clubs#my_index", :as => "my_clubs"
  match "/clubs/destroy/:club_id" => "clubs#destroy"
  match "/clubs/apply/:id" => "clubs#apply", :as => "apply_club"
  match "/clubs/remove/:id" => "clubs#remove", :as => "remove_club"

  resources :teams

  resources :sports


  get "/notifications/show"
  match "/notifications", :to=> 'notifications#show'
  match "/notifications/new", :to => 'notifications#new'
  post "/notifications/create"
  resources :notifications
  

  resources :users
  match "/users" => "users#show"
  match "/recover" => "users#show_recover", :as => "recover_password"
  match "/users/edit_password/:id" => "users#edit_password"
  match "/users/change_password/:id" => "users#change_password"
  match '/signup', :to => 'users#new'
  match '/recover/send', :to => 'users#send_recover'
  match '/password/update', :to => 'users#update_password'
  match "/users/change_password/:id" => "users#change_password", :as => :change_password

  resources :user_verifications
  match "/user_verifications" => "user_verifications#show"

  resources :sessions
  match '/login', :to => 'sessions#new'
  match '/verify' => "sessions#create", :as => :verify_login
  match '/logout', :to => 'sessions#destroy'

  resources :admin_competitions
  match '/competitions/admin', :to => 'admin_competitions#show'
  
  match '/home/help' => 'home#help'
  resources :home


end

clubchief/app/controllers/home_controller.rb
class HomeController < ApplicationController

  def main
  end

  def login  
  	respond_to do |format|
    	format.html { redirect_to login_path}
  	end
  end
end

clubchief/app/helpers/home_helper.rb
module HomeHelper
end

clubchief/app/views/home/_login.html.erb
<h1>Please enter your user details</h1>
<%= form_tag(verify_login_path())  do %>
		<label class="input-label">
    	<%= text_field_tag :email, '', :maxlength => 60,  :class=>"textbox", :placeholder => "Email"  %>
    	</label><br />
    	<label class="input-label">
   		<%= password_field_tag :password, '', :maxlength => 100,  :class=>"textbox" , :placeholder => "Password" %>
   		</label>
    <p>
   	    <%= submit_tag 'Log in', :class=> "button left login_btn" %>
        <div class="left" style="margin-top:20px;">
          <%= link_to "Forgot your password?", recover_password_path , :class => "recover" %><br />
            <%= link_to "Dont have a account?", new_user_path , :class => "register" %>
        </div>
	</p>
  <% end %>

<script type="text/javascript">
   $(function(){	
      $(".textbox").addPlaceholder();
      $("#email").validate({
            expression: "if (VAL.match(/^[^\\W][a-zA-Z0-9\\_\\-\\.]+([a-zA-Z0-9\\_\\-\\.]+)*\\@[a-zA-Z0-9_]+(\\.[a-zA-Z0-9_]+)*\\.[a-zA-Z]{2,4}$/)) return true; else return false;",
            message: "Please enter a valid email",
             error_field_class: "field_with_errors",
            error_class: "error_message"
        });
      $("#password").validate({
            expression: "if (VAL.length > 5 && VAL) return true; else return false;",
            message: "Must contain 6 characters",
            error_field_class: "field_with_errors",
            error_class: "error_message"
        });
        
        
	});
  </script>

clubchief/app/views/home/_recover_password.html.erb
   <h1>Recover Your Password</h1>
   <%= form_tag recover_send_path do %>
    Please provide us with your email that you used to sign up.<br/>

    <br /> 
    <%= text_field_tag :email, "",:id => "recover_email" ,:class => "textbox", :placeholder => "Email"%>
	<br />
	<br />
      <%= submit_tag "Recover", :class => "button left login_btn" %>
        <div class="left" style="margin-top:20px;">
        <%= link_to "Sign up", new_user_path , :class => "register" %><br />
        <%= link_to "Log in", new_session_path , :class => "login" %>
    </div>

   <% end %>
   <br />

   <script type="text/javascript">
   jQuery(function(){
        jQuery("#recover_email").validate({
            expression: "if (VAL.match(/^[^\\W][a-zA-Z0-9\\_\\-\\.]+([a-zA-Z0-9\\_\\-\\.]+)*\\@[a-zA-Z0-9_]+(\\.[a-zA-Z0-9_]+)*\\.[a-zA-Z]{2,4}$/)) return true; else return false;",
            message: "Please enter a valid email",
             error_field_class: "field_with_errors",
            error_class: "error_message"
        });
	});
  </script>

clubchief/app/views/home/_register.html.erb
<h1>Please Register your user details</h1>
<%= form_for User.new  do |f| %>
	<label class="input-label">
        <%= f.text_field :first_name, :class => "textbox" , :placeholder => "First Name" %><br />
    </label>
	<label class="input-label">
        <%= f.text_field :last_name, :class => "textbox" , :placeholder => "Last Name" %><br />
    </label>
	<label class="input-label">
        <%= f.text_field :email, :class => "textbox" , :placeholder => "Email" %><br />
    </label>
	<label class="input-label">
        <%= f.password_field :password, :class => "textbox", :placeholder => "Password"  %> <br />
    </label>
	<label class="input-label">
        <%= f.password_field :password_confirmation, :class => "textbox", :placeholder => "Re-enter Password"  %><br />
     </label>
        <br />
        <%= f.submit "Register", :class => "button edit_btn" %>
        <%= link_to "Already have an account?", new_session_path , :class => "login" %>

      <% end %>
<script type="text/javascript">
   $(function(){
        $("#user_first_name").validate({
            expression: "if (VAL) return true; else return false;",
            message: "Please enter first name",
            error_field_class: "field_with_errors",
            error_class: "error_message"
        });
       $("#user_last_name").validate({
            expression: "if (VAL) return true; else return false;",
            message: "Please enter last name",
            error_field_class: "field_with_errors",
            error_class: "error_message"
        });
        $("#user_email").validate({
            expression: "if (VAL.match(/^[^\\W][a-zA-Z0-9\\_\\-\\.]+([a-zA-Z0-9\\_\\-\\.]+)*\\@[a-zA-Z0-9_]+(\\.[a-zA-Z0-9_]+)*\\.[a-zA-Z]{2,4}$/)) return true; else return false;",
            message: "Please enter a valid email",
             error_field_class: "field_with_errors",
            error_class: "error_message"
        });
        $("#user_password").validate({
            expression: "if (VAL.length > 5 && VAL) return true; else return false;",
            message: "Please enter a valid Password",
            error_field_class: "field_with_errors",
            error_class: "error_message"
        });
        $("#user_password_confirmation").validate({
            expression: "if ((VAL == jQuery('#user_password').val()) && VAL) return true; else return false;",
            message: "Confirm password  doesn't match",
            error_field_class: "field_with_errors",
            error_class: "error_message"
        });
	});
  </script>
      

clubchief/app/views/home/_signed_in.html.erb
    <!-- Initialize Variables -->
    <%
       user = get_current_user
       latest_note = get_user_latest_notification
       latest_event = get_user_latest_event
    %>

    <h1>Welcome back <%=user.full_name%>!</h1>

    <!--Display the latest notification-->
    <b>Latest Notice:</b><br/>
        <% if latest_note != nil %>
            <div>
                <%= latest_note.message %><br />
                <%= link_to "Posted " + time_ago_in_words(latest_note.created_at) + " ago from " + latest_note.team.club.name, notifications_path %>
            </div>
        <% else %>
            <p><i>You don't currently have any recent notifications.</i></p>
        <% end %>
   <br/>

    <!--Display the latest event-->
    <b>Latest Event:</b><br/>
    <div>
        <% if latest_event != nil %>
             <b>Starts:</b> <%=  latest_event.start_at.strftime("%A %b %d   %I:%M%p") %><br/>
             <b>Ends:</b> <%=  latest_event.end_at.strftime("%A %b %d   %I:%M%p") %><br/>
             <b>Details:</b> <%= latest_event.message %><br />
             <b>Created by</b> <%= latest_event.user.full_name %> -
              <%= link_to  time_ago_in_words(latest_event.created_at) + " ago from " + latest_event.team.club.name, latest_event %>
        <% else %>
            <p><i>You don't currently have any recent events.</i></p>
        <% end %>
    </div>
   <!-- Logout button -->
    <%= link_to "Logout", logout_path, :class =>"button edit_btn left"%>
    <%= link_to "Register new club", new_club_path, :class =>"button add_wide_btn left"%>

clubchief/app/views/home/_visitor.html.erb
		<div id="home_title">
			 Easy sports team management
		</div>
		<div  id="visitor_content">

		     <div id="home" class="content_item">
				  	<%= link_to "Sign up", new_user_path , :class => "button left register edit_btn" ,:style=>"margin-top:0;" %>
				    <%= link_to "Log In", new_session_path , :class => "button left login login_btn" ,:style=>"margin-top:0;" %>

				    <div class="clear">
						<p><br/>Club Chief is a sports club management system that provides easy and effective access to club information and events.</p>
						<p>It's your portal to communicate between members and administrators.</p>
						<p>Best of all, it's free!</p>
					</div>
			  </div>
			  <div id="loginBox" class="content_item hidden" style="display: none;" ><%= render "home/login" %></div>
			  <div id="registerBox" class="content_item hidden"><%= render "home/register" %></div>
			  <div id="recoverBox" class="content_item hidden"><%= render "home/recover_password" %></div>
		</div>
		<div class="clear"></div>

    <script>
    	$(".textbox").addPlaceholder();
        $("#visitor_content .content_item").removeClass("hidden");
      	$("#visitor_content .content_item:not(:first)").hide();
        $('.login').live("click",function () {
            $("#visitor_content  .content_item").fadeOut(300);
            $("#visitor_content").delay(200).animate({
              height:"270px"
            },200);
            $("#loginBox").delay(300).fadeIn(300);
            return false;
        });
        $('.register').live("click",function () {
            $("#visitor_content  .content_item").fadeOut(200);

            $("#visitor_content").delay(200).animate({
              height:"350px"
            },200);

            $("#registerBox").delay(300).fadeIn(300, "linear");

            return false;
        });
       $('.recover').live("click",function () {
            $("#visitor_content  .content_item").fadeOut(300);

            $("#visitor_content").delay(200).animate({
              height:"270px"
            },200);

            $("#recoverBox").delay(300).fadeIn(300);
           return false;
        });
    </script>

clubchief/app/views/home/about.html.erb
<h1>About Club Chief</h1>

<div id=content>
<table>
  <tr>
    <td><h2> What do we do? </h2></td>
  </tr>
  <tr>
    <td>Our aim is to provide a system to assist the club managers and their team of volunteers that run their club.

We want to reduce the heavy reliance on club administrator work, give clubs an online
presence, and assist clubs with the facilitation of tournaments, events and practices.
This will allow the club administrators to spend more time on what is important – the
sporting and events themselves.<br>
Also by providing the club with an online service, clubs will become more accessible to
the public making finding members easier and members finding the club easier.<br><br>

<b>Goal:  To reduce the time and hassles for sports club administrators and give
  clubs an online presence. Make it easier for interested parties to join clubs.</b></td>
  </tr>
</table>
</div>

clubchief/app/views/home/contact.html.erb
<h1>Contact Club Chief</h1>

<table>
  <tr>
    <td><h3> send us an email </h3></td>
  </tr>
  <tr>
    <td>"<i>em.clubchief@gmail.com</i>"</td>
  </tr>
</table>

clubchief/app/views/home/help.html.erb
<a name="Top"></a>
<h1>ClubChief Help</h1>
<div class="content round">
  <p>
          <h4>Firstly, welcome to Club Chief we are glad to have you on board!</h4>
  </p>

  <p><h3>Table of Contents</h3>
  <ul>
    <li><a href="#Home">Home Page Help</a></li>
    <li><a href="#Registration">Registration Page Help</a></li>
    <li><a href="#Profile">Profile Page Help</a></li>
    <li><a href="#Clubs">Clubs Page Help</a></li>
    <li><a href="#Calendar">Calendar Page Help</a></li>
    <li><a href="#Competitions">Competitions Page Help</a></li>
    <li><a href="#Notifications">Notifications Page Help</a></li>
  </ul>
  </p>
  <br/>
  <a name="Home"></a>
  <h1>Homepage help: Signing up and logging in</h1>
    <p>Firstly welcome to Club Chief we are glad to have you on board.
        To create yourself an account you can either click Register in the top right menu
        bar or the big Sign up now button at the bottom of the screen.
    </p>

    <img src="/images/help pics 2/home2.png" alt="home2.png" width="500" height="371" />
  <br /><br />

   <h3>Registration page help</h3><a name="Registration"></a>
    <p>When filling out the registration form you will notice that each text box has an
        “*” next to it, this indicates a required field so you must put something
        in the box.
        Once you have filled in each box click the “create user” button.
    </p>


<p>If you have put something in each box but your user account is still not created
check the top of the screen for an error message. It will look something like this:</p>

<img src="/images/help pics/signupsheet.png" alt="signupsheet.png" width="521" height="162" />
  <br /><br />


<p>As you can see the error here is the password is too short. To solve this problem enter
a new password at least 6 characters long.<br>
Other common errors are:<ul>
  <li>Passwords don’t match. You must retype both passwords to ensure they are identical.</li>
  <li>Invalid email address. You cannot sign up without a valid email address. eg. myemail@gmail is invalid. Must be myemail@gmail.com</li>
</ul>
</p>


<h3>Signing in</h3>

<p>Click the “Sign in” link in the top right of your screen, then enter the email
  and password you used to create your account and click “sign in”
  If you cannot remember your password, click “Forgot my password” This will take
  you to account recovery page. If you enter the email you used to sign up and click
  recover you will be emailed a new password.
</p>

<img src="/images/help pics/login.png" alt="login.png" width="521" height="162" />
  <br /><br />







  <a name="Profile"></a>
  <h1>Profile Page</h1><a href="#Top" class="reset">top</a>
  <p>To edit your details or change your password, select View Profile from the
    account actions panel to the right of the screen. If the account options panel
    is not visible click the grey box to the top right of your screen that says Show
    Action Box.
  </p>
  <img src="/images/help pics 2/profile.png" alt="profile.png" width="175" height="300" />
  <img src="/images/help pics 2/sowactions.png" alt="sowactions.png" width="100" height="100" />
  <br /><br />


  <p>All your information can be updated by clicking the Edit Details link located at the bottom of the page.<br>
    You can also change your password from your profile page by clicking the Change Password link
    at the bottom of the page.
  </p>
  <br />


  <a name="Clubs"></a><a href="#Top" class="reset">top</a>
  <h1>Clubs</h1>
  <p>
    To register a new club hover your mouse over the Clubs link in the top menu;
    this will show you a list of options. Go down the list and click Register New Club.
  </p>

  <h3>Your Clubs</h3>
   <p>
    To view a list of all the clubs you are a member or join a new one of hover 
    your mouse over the Clubs link in the top menu; this will show you a list of options.
    Go down the list and click My Clubs. If you are looking to join a club click the
    “Join Clubs!” button.<br></br>
    If you are an admin you can edit club details with the manage link under the clubs name. 
    You can also delete the club with the delete option and assign club members administrator
    status with the Manage option.
   </p>

   <img src="/images/help pics 2/clubs.png" alt="clubs.png" width="521" height="230" />
   
   <h3>Adding Members</h3>
   <p>If you are a club administrator you may want to add members instead of having them
    join themselves, just of hover your mouse over the Clubs link in the top menu;
    this will show you a list of options. Go down the list and click Add Members.
</p>
    


  <a name="Calendar"></a>
  <h1>Calendar Page</h1><a href="#Top" class="reset">top</a>
  <p>The calendar page provides a means for scheduling club events in a fasion that
   allows club members to view and notify of attendance.</p>

  <h3>Adding an event</h3>
  <p>Hover your mouse over the Calendar link in the top menu, this will show you 
    a list of options. Go down the list and click Add Event.<br>
    Give your event a name and provide a message so your members know what’s going on.</p>

  <p>To add a start and end date:
  <ol>
    <li>Click the calendar icon</li>
    <img src="/images/help pics/addevent1.png" alt="addevent1.png" width="200" height="70"  />
    <li>Click a date on the calendar that pops up</li>
    <img src="/images/help pics/addevent2.png" alt="addevent1.png" width="200" height="234"  />
    <li>Adjust the time of the event at the bottom of the popup calendar</li>
   <img src="/images/help pics/addevent3.png" alt="addevent1.png" width="200" height="230"  />
</ol>
</p>




<h3>Adding a team:</h3>
<p>To add a team to the event select a team from the drop down menu. Only teams
  you have admin rights to will be available in the dropdown menu. The entire
  club will appear in the teams’ selection box if you have sufficient rights.
</p>

<img src="/images/help pics/addevent4.png" alt="addevent4.png" width="200" height="210" />
   <br /><br />

<h3>Viewing an event and setting attendance status</h3>
<p>Hover your mouse over the Calendar link in the top menu, this will show you a
  list of options. Go down the list and click Calendar. This will show you a
  calendar with all events relevant to you on it, to view a specific event just
  click on it.
</p>

<img src="/images/help pics 2/calendar.png" alt="calendar.png" width="460" height="370" />
<br>
<p>
  Clicking on an event shows the event details and a list of all members attending.
  If you are not attending click the Not Attending button next to your name. If you
  are a team admin you can set this status for any member. You can change back by
  clicking the button again.
</p>


<img src="/images/help pics 2/viewevent.png" alt="viewevent.png" width="465" height="370" />
<br></br>


<h3>Deleting an event</h3>
<p>Hover your mouse over the Calendar link in the top menu, this will show you a
  list of options. Go down the list and click Calendar.
  This will show you a calendar with all events relevant to you on it,
  click on the event you want to delete. Under the title of the event there is a
  link that says delete.
</p>  <br /><br />



   <a name="Competitions"></a><a href="#top" class="reset">top</a>
   <h1>Competitions</h1>

   <h3>Available Competitions</h3>
   <p>To view all the competitions your club is a part of, hover your mouse over the
      Competitions link in the top menu; this will show you a list of options.
      Go down the list and click Available.<br>
      Once the deadline to enter a competition has passed you can no longer join it
      and it cannot be viewed from this page.</br>
      Note: if your club is only involved with one competition then it is unlikely
      there will be anything here. This is for dividing up different competitions
      the club is a part of (eg. A grade, B grade, Regional Tournament etc.)
   </p>

   <h3>Applications</h3>
   <p>To view all the competitions you have entered in hover your mouse over the
     Competitions link in the top menu; this will show you a list of options.
     Go down the list and click Applications. This is a list of all your pending
     applications.
  </p>


  <h3>Creating competitions</h3>
  <p>To create a competition hover your mouse over the Competitions link in the
    top menu; this will show you a list of options. Go down the list and click Create.
    Give the competition a name and a deadline. The deadline is the last date a
    competition will be available for your members to join.<br>

  If you are the admin of multiple clubs you will have to select a club from the
  drop-down menu.
</p>

<img src="/images/help pics 2/createcomp.png" alt="createcomp.png" width="450" height="230" />
<br>

<h3>Managing competitions</h3>
<p>To manage a competition hover your mouse over the Competitions link in the 
  top menu; this will show you a list of options. Go down the list and click Manage. 
  This provides a list of all competitions you have admin rights to; now just click
  the Manage button next to the competition you want to manage.<br></br>
</p>
  <img src="/images/help pics 2/managecompetitions.png" alt="managecompetitions.png" width="450" height="230" />

  <p>Note: You can only manage a competition once it has met its deadline.<br></br>
  From here you will see a list of all teams that are a part of the competition.
  If there are no teams you can add a new one by entering a team name and
  clicking Create Team.
</p>

<img src="/images/help pics 2/managecompetitions2.png" alt="managecompetitions2.png" width="500" height="400" />

<h3>Managing competition teams</h3>
<p>This feature is used to put members who have applied for the competition into
  the teams that are a part of the competition. If a member did not apply for the
  competition in time but you still want them to in the competition you can add
  them yourself by clicking the Add New Applicants button.<br></br>
  Click the manage link for the team you want to manage.<br></br>
  From here you can remove add players to the team from the pool of
  unassigned players at the bottom of the page, remove players from the team,
  and give them administrator status.
</p>
<img src="/images/help pics 2/managecompetitions3.png" alt="managecompetitions3.png" width="500" height="400" />






  <a name="Notifications"></a>
  <h1>Notifications</h1><a href="#Top" class="reset">top</a>
  <p>To view all notifications relevant to you hover your mouse over the Calendar
    link in the top menu; this will show you a list of options. Go down the list
    and click Notifications.
</p>

<h3>Adding a notification</h3>
<p>To add a notification click the “Add Notification” button at the top of the
  notifications page.
</p>

<img src="/images/help pics/addnotif.png" alt="addnotif.png" width="177" height="100" />

<p>
On the create notifications page fill in the text area with the message you wish to
pass on to your team members, and then select the team.
Note:<ul>
  <li>Message must be more than 10 characters in length</li>
<li>A team must be selected</li>
<li>Message will not be emailed to team members unless “Email team members” is selected.</li>
</ul>
</p>


<h3>Removing/editing a notification</h3>
<p>  On the notifications page, each notification has an edit and a
      delete option next to it which can be used by clicking.<br>
      Similarly there is an edit option which you can click if you need to change
      any aspect of the notification.
  </p>
  <img src="/images/help pics 2/notifications.png" alt="notifications.png" width="550" height="200" />
</div>

clubchief/app/views/home/login.html.erb
<h1>Home#login</h1>

<div id='login_box'>
  <%= form_tag('sessions#create')  do %>
    	email <%= text_field_tag :email %>
    	<br/>
   	Password <%= password_field_tag :password %>
  <% end %>
</div>

clubchief/app/views/home/main.html.erb
<% if logged_in? %>
	<%= render "home/signed_in" %>
<% else %>
	<%= render "home/visitor" %>
<% end %>